### ISSUE TITLE
Looking for some help with the docs

### ISSUE THREAD

**Issue by JiDW** [oguzeroglu/TextureMerger#1]
Hello!

Thank you for sharing this very cool lib, it's exactly what I was looking for!

While trying to use it, I looked at your live demo and the documentation.
Unfortunately, as a beginner, I don't understand what should be done (where and how) with the shaders, and the live demo doesn't use this at all.

Would you mind giving me more infos please?

Regards.

**Comment by oguzeroglu** [comment]
Hey!

In the example, I directly modify the geometry so that the modified UV coordinates are passed to the shader. You can do that if you don't want to write custom shaders.

If you want to write custom shaders, you're going to have to pass the `startU`, `endU`, `startV`, `endV` values calculated by TextureMerger to your shader (either as an attribute or uniform). You then need to modify the original UV coordinates of your geometry with the formula I've written in the README and do the texture lookup with the modified UV coordinates rather than the original ones. You can apply the formula either inside the vertex shader or in the fragment shader.

If you're not familiar with writing custom shaders I'd suggest you to use the first approach (the approach that is used by the example).

**Why modifying the original UV coordinates?**
UV coordinates normally belong to the [0, 1] range. 0 representing the start of the image and 1 the end. Since now we're using multiple images, we need to map:

* Original U from [0, 1] range to [startU, endU] range
* Original V from [0, 1] range to [startV, endV] range

Hope it makes sense!
